---
# tasks file for roles/install-galera
- name: Install MariaDB
  apt:
    name: '{{ item }}'
    state: present
  loop:
  - mariadb-server
  - mariadb-client

- name: Open firewalld ports
  firewalld:
    port: '{{ item }}'
    permanent: yes
    immediate: yes
    state: enabled
  loop:
  - 3306/tcp  # MariaDB
  - 4567/tcp  # Galera Replication
  - 4568/tcp  # IST Incremental State Transfers
  - 4444/tcp  # SST State Snapshot Transfer

- name: Start MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Install pymysql
  pip:
    name: pymysql
    state: present

- name: Secure MariaDB
  include: secure-mysql.yml

- name: Check if galera already configured
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    line: bind-address=0.0.0.0
    state: present
  register: galera_conf
  when: ansible_host == groups['masters'][0]

- name: Copy galera bootstrap config
  template:
    src: templates/50-server.cnf.bootstrap.j2
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    owner: root
    group: root
    mode: '0644'
  when: galera_conf.changed and ansible_host == groups['masters'][0]
  register: bootstrap

- name: Bootstrap galera cluster
  service:
    name: mariadb
    state: restarted
  when: bootstrap.changed and ansible_host == groups['masters'][0]

- name: Prepare k3s database
  include: k3s-db.yml
  when: bootstrap.changed and ansible_host == groups['masters'][0]

- name: Copy galera configuration
  template:
    src: templates/50-server.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    owner: root
    group: root
    mode: '0644'
  register: galera_configured

- name: Activate galera
  service:
    name: mariadb
    state: restarted
  delegate_to: '{{ item }}'
  run_once: yes
  loop: "{{ groups['masters'][1:] }}"
  when: galera_configured.changed and ansible_host in groups['masters'][1:]
