---
# tasks file for roles/upgrade-k3s
- name: upgrade master
  shell: curl -sfL https://get.k3s.io | sh -
  when: ansible_host in groups['master']

- name: get node token
  shell: cat /var/lib/rancher/k3s/server/node-token
  register: node_token
  delegate_to: "{{ groups['master'][0] }}"

- name: install nodes
  shell: curl -sfL https://get.k3s.io | \
    K3S_URL=https://{{ hostvars[groups['master'][0]].ansible_default_ipv4.address }}:6443 \
    K3S_TOKEN={{ node_token.stdout }} \
    sh -
  when: ansible_host in groups['workers']

- name: restart k3s
  service:
    name: k3s
    state: restarted
  when: ansible_host in groups['master']
