---
# tasks file for roles/k3s-ufw
- name: Start ufw
  ufw:
    state: enabled

- name: Open k3s ports
  ufw:
    port: '{{ item }}'
    rule: allow
    proto: tcp
  loop:
  - '80'
  - '443'
  - '6443'  # Kubernetes API
  - '8472'  # Required only for Flannel VXLAN
  - '10250' # kubelet
