---
# tasks file for roles/upgrade-k3s-ha
- name: Upgrade masters
  shell: curl -sfL https://get.k3s.io | \
    sh -s - server \
    --datastore-endpoint="{%- for host in groups['masters'] -%}
      http://{{ host }}:2379{{ "," if not loop.last }}
    {%- endfor -%}"
  run_once: yes
  loop: "{{ groups['masters'] }}"

- name: Get node token
  shell: cat /var/lib/rancher/k3s/server/node-token
  register: token_file
  delegate_to: "{{ groups['masters'][0] }}"

- set_fact:
    node_token: '{{ token_file.stdout }}'

- name: Install workers
  shell: curl -sfL https://get.k3s.io | \
    K3S_URL=https://{{ hostvars[groups['masters'][0]].ansible_default_ipv4.address }}:6443 \
    K3S_TOKEN={{ node_token }} \
    sh -
  when: ansible_host in groups['workers']

- name: restart k3s
  service:
    name: k3s
    state: restarted
  delegate_to: '{{ item }}'
  run_once: yes
  loop: "{{ groups['masters'] }}"
