---
# tasks file for roles/install-k3s
- name: install k3s SELinux support
  yum:
    name: '{{ item }}'
    state: present
  when: ansible_distribution_file_variety == "RedHat"

- name: Verify cgroup flags are enabled
  shell: grep "{{ item }}" /boot/cmdline.txt || sed -i 's/\(.*\)/\1 {{ item }}/g' /boot/cmdline.txt || touch /tmp/cgroup.reboot
  loop:
    - 'cgroup\_enable\=cpuset'
    - 'cgroup\_enable\=memory'
    - 'cgroup\_memory\=1'

- name: Check if cgroups changed
  stat:
    path: /tmp/cgroup.reboot
  register: cgroup_reboot

- name: Reboot to apply cgroups
  reboot:
  when: cgroup_reboot.stat.exists

- name: reboot to apply cgroups
  reboot:

- name: install master
  shell: curl -sfL https://get.k3s.io | sh -
  args:
    creates: /var/lib/rancher/k3s/server/node-token
  when: ansible_host == groups['masters'][0]

- name: Get node token
  shell: cat /var/lib/rancher/k3s/server/node-token
  register: token_file
  delegate_to: "{{ groups['masters'][0] }}"

- set_fact:
    node_token: '{{ token_file.stdout }}'

- name: install nodes
  shell: curl -sfL https://get.k3s.io | \
    K3S_URL=https://{{ hostvars[groups['masters'][0]].ansible_default_ipv4.address }}:6443 \
    K3S_TOKEN={{ node_token }} \
    sh -
  args:
    creates: /var/lib/rancher/k3s/agent/client-ca.crt
  when: ansible_host in groups['workers']

- name: create k3s.yaml.orig
  copy:
    remote_src: yes
    src: /etc/rancher/k3s/k3s.yaml
    dest: /etc/rancher/k3s/k3s.yaml.orig
    force: no
  when: ansible_host == groups['masters'][0]

- name: modify k3s.yaml with master hostname
  replace:
    path: /etc/rancher/k3s/k3s.yaml
    regexp: "server: https://127.0.0.1:6443"
    replace: "server: https://{{ hostvars[groups['masters'][0]].ansible_hostname }}:6443"
  when: ansible_host == groups['masters'][0]

- name: get kube config
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: k3s.yaml
    mode: 0600
    flat: yes
  when: ansible_host == groups['masters'][0]
