---
- name: Update all packages
  apt:
    name: '*'
    state: latest
    update_cache: yes
    autoremove: yes
  register: updated

- name: Remove ufw
  apt:
    name: ufw
    state: absent

- name: Install firewalld
  apt:
    name: firewalld
    state: present

- name: Reboot hosts if updated
  reboot:
  when: updated.changed

- name: Expand rootfs of Raspbian
  command: raspi-config --expand-rootfs
  ignore_errors: yes
