---
- name: Update all packages
  apt:
    name: '*'
    state: latest
    update_cache: yes
    autoremove: yes
  register: updated

- name: Install required pacakges
  apt:
    name: '{{ item }}'
    state: present
  loop:
  - ufw
  - python3-pip
#  - python-setuptools

- name: Reboot hosts if updated
  reboot:
  when: updated.changed
