---
- name: Update all packages
  apt:
    name: '*'
    state: latest
    update_cache: yes
    autoremove: yes
  register: updated

- name: Install required packages
  apt:
    name: '{{ item }}'
    state: present
  loop:
  - python3-pip
  - python-setuptools

- name: Reboot hosts if updated
  reboot:
  when: updated.changed
 
- name: Expand rootfs of Raspbian
  command: raspi-config --expand-rootfs
  ignore_errors: yes
