---
- name: Install prerequirements
  yum:
    name: '{{ item }}'
    state: present
  loop:
  - lvm2
  - thin-provisioning-tools
  - xfsprogs
  - centos-release-gluster
  - epel-release

- name: Install gluster packages
  yum:
    name: '{{ item }}'
    state: present
  loop:
  - glusterfs-server
  - glusterfs-client
