---
# tasks file for roles/install-k3sup-ha
- name: Install k3s SELinux support
  yum:
    name: '{{ item }}'
    state: present
  loop:
  - container-selinux
  - selinux-policy-base
  - https://rpm.rancher.io/k3s-selinux-0.1.1-rc1.el7.noarch.rpm
  when: ansible_distribution_file_variety == "RedHat"

- name: Verify cgroup flags are enabled
  shell: grep "{{ item }}" /boot/cmdline.txt || sed -i 's/\(.*\)/\1 {{ item }}/g' /boot/cmdline.txt || touch /tmp/cgroup.reboot
  loop:
    - 'cgroup\_enable\=cpuset'
    - 'cgroup\_enable\=memory'
    - 'cgroup\_memory\=1'

- name: Check if cgroups changed
  stat:
    path: /tmp/cgroup.reboot
  register: cgroup_reboot

- name: Reboot to apply cgroups
  reboot:
  when: cgroup_reboot.stat.exists

- name: Check if k3sup already installed
  stat:
    path: /usr/local/bin/k3sup
  register: k3sup_bin

- name: Download k3sup install script
  get_url:
    url: https://get.k3sup.dev
    dest: /tmp/getk3sup.sh
    mode: '0755'
  when: not k3sup_bin.stat.exists

- name: Install k3sup
  command: /tmp/getk3sup.sh
  when: not k3sup_bin.stat.exists

- name: Install initial master
  command:
  args:
    argv:
    - k3sup
    - install
    - --ip
    - "{{ hostvars[groups['masters'][0]].ansible_default_ipv4.address }}"
    - --user
    - '{{ root.username }}'
    - --ssh-key
    - "{{ root.remote_keypath }}/{{ root.keyfile }}"
    #- --k3s-version
    #- '{{ k3s.version }}'
    - --cluster
    creates: /var/lib/rancher/k3s/server/node-token
  when: ansible_host == groups['masters'][0]

- name: Install masters
  command:
  args:
    argv:
    - k3sup
    - join
    - --ip
    - "{{ hostvars[item].ansible_default_ipv4.address }}"
    - --user
    - '{{ root.username }}'
    - --server-user
    - '{{ root.username }}'
    - --server-ip
    - "{{ hostvars[groups['masters'][0]].ansible_default_ipv4.address }}"
    - --ssh-key
    - "{{ root.remote_keypath }}/{{ root.keyfile }}"
    #- --k3s-version
    #- '{{ k3s.version }}'
    - --server
  when: ansible_host == groups['masters'][0]
  loop: "{{ groups['masters'][1:] }}"
  ignore_errors: yes

- name: Ensure k3s is running on masters
  service:
    name: k3s
    state: started
    enabled: yes
  when: ansible_host in groups['masters']

- name: Install workers
  command:
  args:
    argv:
    - k3sup
    - join
    - --ip
    - "{{ hostvars[item].ansible_default_ipv4.address }}"
    - --server-ip
    - "{{ hostvars[groups['masters'][0]].ansible_default_ipv4.address }}"
    - --user
    - '{{ root.username }}'
    - --ssh-key
    - "{{ root.remote_keypath }}/{{ root.keyfile }}"
    #- --k3s-version
    #- '{{ k3s.version }}'
  when: ansible_host == groups['masters'][0]
  loop: "{{ groups['workers'] }}"

- name: create k3s.yaml.orig
  copy:
    remote_src: yes
    src: /etc/rancher/k3s/k3s.yaml
    dest: /etc/rancher/k3s/k3s.yaml.orig
    force: no
  when: ansible_host == groups['masters'][0]

- name: modify k3s.yaml with VIP
  replace:
    path: /etc/rancher/k3s/k3s.yaml
    regexp: "server: https://127.0.0.1:6443"
    replace: "server: https://{{ vip.ip }}:6443"
  when: ansible_host == groups['masters'][0]

- name: get kube config
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: k3s.yaml
    mode: 0600
    flat: yes
  when: ansible_host == groups['masters'][0]
