---
- name: Configure the PiKubed cluster
  hosts: pikubed_cluster
  become: true
  vars_files: vars.yml
  pre_tasks:
  - name: Update packages
    yum:
      name: '*'
      state: latest
      update_cache: yes

  #- name: Create /etc/hosts
    #template:
      #src: templates/hosts.j2
      #dest: /etc/hosts
      #owner: root
      #group: root

  - name: Move /tmp to tmpfs
    mount:
      path: /tmp
      src: tmpfs
      fstype: tmpfs
      opts: rw,nodev,nosuid
      state: mounted

  roles:
  - role: log2ram
  - role: install-k3s
  - role: keepalived-vip
    vars:
    - vip_pass: '{{ vip.pass }}'
    - vip_ip: '{{ vip.ip }}'
