---
- name: Remove logical and GlusterFS persistent volumes
  hosts: pikubed_cluster
  become: true
  remote_user: '{{ ansible.username }}'
  vars_files: vars.yml
  tasks:

  - name: Unmount GlusterFS volumes
    mount:
      path: '{{ gluster_mount}}/{{ item }}'
      state: absent
    loop: '{{ lvs_remove }}'

  - name: Remove GlusterFS volumes
    gluster_volume:
      state: absent
      name: '{{ item }}'
    loop: '{{ lvs_remove }}'
    run_once: yes

  - name: Unmount bricks
    mount:
      path: '{{ brick_mount}}/{{ item }}'
      state: absent
    loop: '{{ lvs_remove }}'

  - name: Remove brick mountpoints
    file:
      path: '{{ brick_mount}}/{{ item }}'
      state: absent
    loop: '{{ lvs_remove }}'

  - name: Remove logical volumes
    lvol:
      vg: '{{ vg.name }}'
      thinpool: '{{ tpool.name }}'
      lv: '{{ item }}'
      state: absent
      force: yes
    loop: '{{ lvs_remove }}'
