---
- name: Configure Raspberry Pi Hosts
  hosts: pikubed_cluster
  remote_user: ubuntu
  become: yes
  vars_files: vars.yml

  roles:
  - role: common
    tags: setup-hosts

  - role: log2ram
    vars:
    - log_folder_size: '{{ log2ram.folder_size }}'

  # Used only if using k3sup
  #- role: distribute-sshkey
  #  vars:
  #    keyuser: '{{ root.username }}'
  #    keypath: '{{ root.keypath }}'
  #    keyfile: '{{ root.keyfile }}'
  #    remote_keypath: '{{ root.remote_keypath }}'
  #  tags: distribute-sshkeys

  - role: keepalived-vip
    vars:
    - vip_pass: '{{ vip.pass }}'
    - vip_ip: '{{ vip.ip }}'
    when: vip_priority is defined
    tags: setup-vip

  - role: install-galera
    vars:
    - db_root_password: '{{ mysql.root_pass }}'
    when: ansible_host in groups['masters']
    tags: setup-galera

  - role: k3s-firewalld

  - role: install-k3s-ha
    tags: setup-k3s

  #- role: install-heketi
