---
- name: Configure Raspberry Pi Hosts
  hosts: pikubed_cluster
  remote_user: '{{ root.username }}'
  become: yes
  vars_files:
  - vars.yml

  roles:
  - role: common
    tags: common

  - role: log2ram
    vars:
    - log_folder_size: '{{ log2ram.folder_size }}'
    tags: log2ram

  - role: keepalived-vip
    vars:
    - vip_pass: '{{ vip.pass }}'
    - vip_ip: '{{ vip.ip }}'
    when: vip_priority is defined
    tags: vip

  - role: install-etcd
    when: ansible_host in groups['masters']
    rags: etcd

  - role: k3s-ufw
    tags: k3s

  - role: install-k3s-ha
    tags: k3s

  - role: configure-kadalu
    tags: kadalu
