---
- name: Upgrade K3S
  hosts: pikubed_cluster
  become: yes
  roles:
  - role: upgrade-k3s

- name: Update and reboot nodes one at a time
  hosts: pikubed_cluster
  become: yes
  serial: 1
  gather_facts: no
  tasks:

  - name: Update node
    yum:
      name: '*'
      state: latest
      update_cache: yes
    register: updated

  - name: Reboot node
    reboot:
    when: updated.changed
