---
- name: Upgrade K3S
  hosts: pikubed_cluster
  become: yes
  remote_user: '{{ ansible.username }}'
  vars_files: vars.yml
  roles:
  - role: upgrade-k3s-ha

- name: Update and reboot nodes one at a time
  hosts: pikubed_cluster
  become: yes
  remote_user: '{{ ansible.username }}'
  serial: 1
  gather_facts: no
  tasks:

  - name: Update node (yum)
    yum:
      name: '*'
      state: latest
      update_cache: yes
    register: updated
    when: ansible_distribution_file_variety == "RedHat"

  - name: Update node (apt)
    apt:
      name: '*'
      state: latest
      update_cache: yes
      autoremove: yes
    register: updated
    when: ansible_distribution_file_variety == "Debian"

  - name: Reboot node
    reboot:
      test_command: systemctl is-active etcd.service
    when: ansible_host in groups['masters'] and updated.changed

  - name: Reboot node
    reboot:
    when: ansible_host not in groups['masters'] and updated.changed
